import {
  Activity,
  Factory,
  Hammer,
  Truck,
  Bell,
  Bot,
  Calendar,
  Car,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileText,
  LayoutDashboard,
  MessageSquare,
  Package,
  Receipt,
  Settings,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { ModuleKey } from "@/lib/constants";

export const NAV_ICON: Record<ModuleKey | "dashboard" | "settings", LucideIcon> = {
  dashboard: LayoutDashboard,
  vehicles: Car,
  customers: Users,
  workOrders: ClipboardList,
  schedule: Calendar,
  estimates: FileText,
  invoices: Receipt,
  parts: Package,
  jobs: Factory,
  tooling: Hammer,
  shipments: Truck,
  technicians: Wrench,
  inspections: ClipboardCheck,
  reports: LayoutDashboard,
  payments: CreditCard,
  ai: Bot,
  production: Activity,
  messages: MessageSquare,
  notifications: Bell,
  settings: Settings,
};
